package app.proyecto.view;

import app.proyecto.db.AccesoDB;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class Consultas extends javax.swing.JFrame {
    AccesoDB conn = new AccesoDB();
    
    public Consultas() {
        initComponents();
        this.setTitle("Consultas");
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        conn.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnVolver4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        jButton9.setText("Empresas Laboradas");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setText("Idioma");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setText("CV datos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ver datos básicos de:");

        jButton3.setText("Educ. Escolar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Postulante");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVolver4.setText("Volver al menu");
        btnVolver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton13.setText("Postulante mas longevo");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton12.setText("Postulantes 013ACE");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton11.setText("Numero de Postulantes");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel3.setText("Consultas Específicas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton11)
                                .addGap(38, 38, 38)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton9)
                            .addComponent(jButton13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btnVolver4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(18, 18, 18)
                .addComponent(btnVolver4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/buscar.png"))); // NOI18N
        jLabel4.setText("CONSULTAS");

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Datos Basicos");
        jMenu1.setAlignmentX(0.0F);

        jMenuItem1.setText("Postulante");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Educ. Escolar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Idioma");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Empresas Laboradas");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas Especifica");

        jMenuItem5.setText("Numero de Postulantes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Postulantes mas longevo");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ResultSet r = conn.Consultar("SELECT ID_POSTULANTE, CODPUESTO, NOMBRE, APPATERNO,APMATERNO,FECNAC,TELEFONO1 FROM POSTULANTE"); 
        DefaultTableModel modelo = new DefaultTableModel(); 
        jTable1.setModel(modelo); 
         modelo.addColumn("ID"); 
         modelo.addColumn("CODPUESTO"); 
         modelo.addColumn("NOMBRE"); 
         modelo.addColumn("APPATERNO"); 
         modelo.addColumn("APMATERNO");
         modelo.addColumn("FEC_NAC");
         modelo.addColumn("TELEFONO1");
         
         try { 
            while(r.next()){ 
               Object [] fila = new Object[7];//Crea un vector 
               //para almacenar los valores del ResultSet 
              for (int i=0;i<7;i++) 
              fila[i] = r.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1. 
               //añado el modelo a la tabla 
               modelo.addRow(fila); 
               fila=null;//limpia los datos de el vector de la memoria 
            } 
            r.close();//cerrar result-set 
        } catch (SQLException ex) { 
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      
        ResultSet r = conn.Consultar("SELECT * FROM COLEGIO");      

        DefaultTableModel modelo = new DefaultTableModel(); 
        jTable1.setModel(modelo); 
         modelo.addColumn("ID_COLEGIO"); 
         modelo.addColumn("NOMBRE"); 
         modelo.addColumn("PAIS"); 
         
         try { 
            while(r.next()){ 
               Object [] fila = new Object[3];//Crea un vector 
               //para almacenar los valores del ResultSet 
              for (int i=0;i<3;i++) 
              fila[i] = r.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1. 
               //añado el modelo a la tabla 
               modelo.addRow(fila); 
               fila=null;//limpia los datos de el vector de la memoria 
            } 
            r.close();//cerrar result-set 
        } catch (SQLException ex) { 
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    
        ResultSet r = conn.Consultar("SELECT ID_CV,FEC_CV,EJFUN_PUBLICA,INF_ADICIONAL FROM CV");      

        DefaultTableModel modelo = new DefaultTableModel(); 
        jTable1.setModel(modelo); 
         modelo.addColumn("ID_CV"); 
         modelo.addColumn("FECHA_CV"); 
         modelo.addColumn("EJFUN_PUBLICA");
         modelo.addColumn("INFORMACION ADICIONAL"); 
         
         try { 
            while(r.next()){ 
               Object [] fila = new Object[4];//Crea un vector 
               //para almacenar los valores del ResultSet 
              for (int i=0;i<4;i++) 
              fila[i] = r.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1. 
               //añado el modelo a la tabla 
               modelo.addRow(fila); 
               fila=null;//limpia los datos de el vector de la memoria 
            } 
            r.close();//cerrar result-set 
        } catch (SQLException ex) { 
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    
        ResultSet r = conn.Consultar("SELECT * FROM DETALLE_IDIOMA"); 
        String sql;

        DefaultTableModel modelo = new DefaultTableModel(); 
        jTable1.setModel(modelo); 
         modelo.addColumn("ID_CV"); 
         modelo.addColumn("ID_IDIOMA"); 
         modelo.addColumn("LEE");
         modelo.addColumn("HABLA"); 
         modelo.addColumn("ENTIENDE"); 
         modelo.addColumn("ESCRIBE"); 
         
         try { 
            while(r.next()){ 
               Object [] fila = new Object[6];//Crea un vector 
               //para almacenar los valores del ResultSet 
              for (int i=0;i<6;i++) 
              fila[i] = r.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1. 
               //añado el modelo a la tabla 
               modelo.addRow(fila); 
               fila=null;//limpia los datos de el vector de la memoria 
            } 
            r.close();//cerrar result-set 
        } catch (SQLException ex) { 
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        ResultSet r = conn.Consultar("SELECT * FROM  EMPRESA"); 
        String sql;

        DefaultTableModel modelo = new DefaultTableModel(); 
        jTable1.setModel(modelo); 
         modelo.addColumn("ID_EMPRESA"); 
         modelo.addColumn("NOMBRE"); 
         modelo.addColumn("SECTOR"); 
         modelo.addColumn("RUBRO");
         modelo.addColumn("LUGAR");
         modelo.addColumn("TELEFONO");
         
         try { 
            while(r.next()){ 
               Object [] fila = new Object[6];//Crea un vector 
               //para almacenar los valores del ResultSet 
              for (int i=0;i<6;i++) 
              fila[i] = r.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1. 
               //añado el modelo a la tabla 
               modelo.addRow(fila); 
               fila=null;//limpia los datos de el vector de la memoria 
            } 
            r.close();//cerrar result-set 
        } catch (SQLException ex) { 
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
     
        ResultSet r = conn.Consultar("select min(FECNAC) from POSTULANTE");      

        DefaultTableModel modelo = new DefaultTableModel(); 
        jTable1.setModel(modelo); 
         modelo.addColumn("Fecha de nacimiento del postulante mas longevo"); 
         
         try { 
            while(r.next()){ 
               Object [] fila = new Object[1];//Crea un vector 
               //para almacenar los valores del ResultSet 
              for (int i=0;i<1;i++) 
              fila[i] = r.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1. 
               //añado el modelo a la tabla 
               modelo.addRow(fila); 
               fila=null;//limpia los datos de el vector de la memoria 
            } 
            r.close();//cerrar result-set 
        } catch (SQLException ex) { 
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     
        ResultSet r = conn.Consultar("SELECT ID_POSTULANTE, CODPUESTO, NOMBRE, APPATERNO,APMATERNO,FECNAC,TELEFONO1 FROM POSTULANTE WHERE codpuesto='013ACE'");      

        DefaultTableModel modelo = new DefaultTableModel(); 
        jTable1.setModel(modelo); 
         modelo.addColumn("ID"); 
         modelo.addColumn("CODPUESTO"); 
         modelo.addColumn("NOMBRE"); 
         modelo.addColumn("APPATERNO"); 
         modelo.addColumn("APMATERNO");
         modelo.addColumn("FEC_NAC");
         modelo.addColumn("TELEFONO1");
         
         try { 
            while(r.next()){ 
               Object [] fila = new Object[7];//Crea un vector 
               //para almacenar los valores del ResultSet 
              for (int i=0;i<7;i++) 
              fila[i] = r.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1. 
               //añado el modelo a la tabla 
               modelo.addRow(fila); 
               fila=null;//limpia los datos de el vector de la memoria 
            } 
            r.close();//cerrar result-set 
        } catch (SQLException ex) { 
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        ResultSet r = conn.Consultar("select count (*) from POSTULANTE");      

        DefaultTableModel modelo = new DefaultTableModel(); 
        jTable1.setModel(modelo); 
         modelo.addColumn("Cantidad de Postulantes"); 
         
         try { 
            while(r.next()){ 
               Object [] fila = new Object[1];//Crea un vector 
               //para almacenar los valores del ResultSet 
              for (int i=0;i<1;i++) 
              fila[i] = r.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1. 
               //añado el modelo a la tabla 
               modelo.addRow(fila); 
               fila=null;//limpia los datos de el vector de la memoria 
            } 
            r.close();//cerrar result-set 
        } catch (SQLException ex) { 
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnVolver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver4ActionPerformed
        new Inicio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolver4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
